### ISSUE TITLE
Consider using polint and dennis instead

### ISSUE THREAD

**Issue by sobolevn** [Junte/docker-django-quality#6]
Hi! I found this project and just wanted to share that we solve the same problem with `dennis` and `polint`: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker/ci.sh#L67-L73

It might be useful to you as well!

**Comment by lapshin1988** [comment]
Hi! Thank you! We will try to use it 👍

**Comment by slapshin** [comment]
We decided not to use a shared image to check the quality of the code: each project should decide how it should be checked and which libraries (and their versions) should be used. Thanks for the great advice! We are currently using the suggested libraries (`dennis` and `polint`) to validate the project
